### ISSUE TITLE
Remove threads dependency from Makefile.PL for thread-less perls

### ISSUE THREAD

**Issue by burak** [alambike/eixo-docker#15]
`# check if threads are available
BEGIN {
    die("OS unsupported:  ERROR: This Perl not built to support threads\n")
        if (! $Config{'useithreads'});
}`

This means that perls without threads can't install the module by automated tooling and the module set itself does not make any use of threads.

**Comment by burak** [comment]
Hmm nevermind I was wrong about this apparently

**Comment by frankiejol** [comment]
Hey @burak, thanks for stopping by anyway
