### ISSUE TITLE
Connection to Docker host via https fails on Mac OSX 10.9.5 / docker-machine

### ISSUE THREAD

**Issue by matrixritter** [alambike/eixo-docker#7]
I'm using Mac OSX 10.9.5 and my Docker environment is like this:

    $ docker -v
    Docker version 1.9.0, build 76d6bc9
    $ docker-machine -v
    docker-machine version 0.5.0 (04cfa58)
    $ docker-machine env default
    export DOCKER_TLS_VERIFY="1"
    export DOCKER_HOST="tcp://192.168.99.100:2376"
    export DOCKER_CERT_PATH="/Users/kkruse/.docker/machine/machines/default"
    export DOCKER_MACHINE_NAME="default"
    # Run this command to configure your shell: 
    # eval "$(docker-machine env default)"

The supplied openssl is 0.9.8zg:

    $ openssl version
    OpenSSL 0.9.8zg 14 July 2015

The perl version in use is 5.14.4:
    
    $ perl -v
    This is perl 5, version 14, subversion 4 (v5.14.4) built for darwin-2level

My own code for optaining an API object is nearly identical to the example code, but fails with a SSL error. Running with `use IO::Socket::SSL qw(debug4);` as suggested leads to this debug messages:

```
DEBUG: .../IO/Socket/SSL.pm:2688: new ctx 140474202101584
DEBUG: .../IO/Socket/SSL.pm:605: socket not yet connected
DEBUG: .../IO/Socket/SSL.pm:607: socket connected
DEBUG: .../IO/Socket/SSL.pm:629: ssl handshake not started
DEBUG: .../IO/Socket/SSL.pm:671: not using SNI because openssl is too old
DEBUG: .../IO/Socket/SSL.pm:716: set socket to non-blocking to enforce timeout=180
DEBUG: .../IO/Socket/SSL.pm:729: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:732: done Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:742: ssl handshake in progress
DEBUG: .../IO/Socket/SSL.pm:752: waiting for fd to become ready: SSL wants a read first
DEBUG: .../IO/Socket/SSL.pm:772: socket ready, retrying connect
DEBUG: .../IO/Socket/SSL.pm:729: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:2542: ok=0 [0] /O=kkruse/O=kkruse.default
DEBUG: .../IO/Socket/SSL.pm:732: done Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:735: SSL connect attempt failed

DEBUG: .../IO/Socket/SSL.pm:735: local error: SSL connect attempt failed error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
DEBUG: .../IO/Socket/SSL.pm:738: fatal SSL error: SSL connect attempt failed error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
DEBUG: ...14.4/Net/HTTPS.pm:69: ignoring less severe local error 'IO::Socket::INET configuration failed', keep 'SSL connect attempt failed error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed'
DEBUG: .../IO/Socket/SSL.pm:2721: free ctx 140474202101584 open=140474202101584
DEBUG: .../IO/Socket/SSL.pm:2726: free ctx 140474202101584 callback
DEBUG: .../IO/Socket/SSL.pm:2733: OK free ctx 140474202101584
Uncaught exception from user code:
	Remote Api error: (500). Details: Can't connect to 192.168.99.100:2376 (certificate verify failed)

LWP::Protocol::https::Socket: SSL connect attempt failed error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed at /Users/kkruse/perl5/perlbrew/perls/perl-5.14.4/lib/site_perl/5.14.4/LWP/Protocol/http.pm line 47.
```
According to several print statements introduced in the Api.pm, my paths provided are correct. The error message is the same with correct or intentional wrong paths. This leads me to the conclusion that the certificates provided are not used. 
Connecting with openssl and the certificates works:
```
$ openssl s_client -tls1 -CAfile ${DOCKER_CERT_PATH}/ca.pem -key ${DOCKER_CERT_PATH}/key.pem -cert ${DOCKER_CERT_PATH}/cert.pem -connect 192.168.99.100:2376
CONNECTED(00000003)
depth=1 /O=kkruse
verify return:1
depth=0 /O=kkruse.default
verify return:1
---
Certificate chain
 0 s:/O=kkruse.default
   i:/O=kkruse
---
```

**Comment by alambike** [comment]
Hi, I just install docker-machine and try the connection with a new azure host, and everything work fine, so can't reproduce the error. :-(

I send you an email with my test certs so you can make the same check.

Maybe the problem is with perl stack, I was making the tests in Ubuntu 14.04, with 
- perl 5.18.2 
- openSSL 1.0.1f, 
- Eixo::Docker 1.210, recent intallation with cpanminus
   - Eixo::Rest 1.032
   - IO::Socket::SSL 2.021
   - Net::HTTPS 6.09
   - Net::SSLeay  1.72
   - LWP 6.15

**Comment by alambike** [comment]
Closed! Upgrading perl stack solve the issue, probably some incompatibility between SSL protocols accepted by docker api, and old libraries in the client side.
